dist: trusty
sudo: false
language: node_js
node_js:
  - "7"

install:
  - npm install -g truffle
  - npm install -g truffle-expect
  - npm install -g truffle-config
  - npm install -g ethereumjs-testrpc

before_script:
  - testrpc --l 5000000 > testrpc.log &

script:
  - truffle test
