sudo: required
language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules

before_install:
  - npm install -g ethereumjs-testrpc
  - testrpc &
  - truffle migrate

script:
  - truffle test
  - npm run build

